include: package:pedantic_mono/analysis_options.yaml

linter:
  rules:
    avoid_catches_without_on_clauses: false
    flutter_style_todos: false
    lines_longer_than_80_chars: false

analyzer:
    exclude:
        # ファイルを直接指定
        # - lib/client.dart
        # フォルダ内の特定の文字列を指定
        - lib/generated*
        - lib/**/*.freezed.dart
        # フォルダ内の全てのファイルを指定
        # - test/_data/**
